name: Deploy GitHub Pages from /quiz-app

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: quiz-app

      # Workaround: force GitHub to use upload-artifact@v4 instead of the old v3
      - name: Dummy artifact upload to override v3
        uses: actions/upload-artifact@v4
        with:
          name: dummy
          path: README.md
          if-no-files-found: ignore

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
